version: '3.8'

services:
  dht22-monitor:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - DATABASE_PATH=/app/data/environmental_monitoring.db
    restart: unless-stopped
    container_name: dht22-monitor

  dht22-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - DEBUG=true
    container_name: dht22-dev
