name: Quality & Security Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Auto-fix common issues
        run: python tools/quality/auto_fix_common_issues.py

      - name: Find security issues
        run: python tools/quality/find_security_issues.py

      - name: TruffleHog DHT22 scan
        run: python tools/git_commit_check/trufflehog_scan.py --filesystem --privacy-mode --verbose
